<a href="https://colab.research.google.com/github/jothi08/Deeplearning_Feb21_2026/blob/main/Simple_RNN_IMDB/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#implementing word embedding with Keras Tensorflow

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
for words in sent:
  print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[7147, 9303, 4510, 7604],
 [7147, 9303, 4510, 8671],
 [7147, 4870, 4510, 3194],
 [6447, 5782, 2541, 9116, 4673],
 [6447, 5782, 2541, 9116, 2785],
 [8410, 7147, 5911, 4510, 9087],
 [9273, 9618, 6576, 9116]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7147 9303 4510 7604]
 [   0    0    0    0 7147 9303 4510 8671]
 [   0    0    0    0 7147 4870 4510 3194]
 [   0    0    0 6447 5782 2541 9116 4673]
 [   0    0    0 6447 5782 2541 9116 2785]
 [   0    0    0 8410 7147 5911 4510 9087]
 [   0    0    0    0 9273 9618 6576 9116]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step


array([[[-4.3687463e-02, -3.5354652e-02,  4.2295184e-02,  4.0213589e-02,
          4.0062655e-02, -3.5295881e-02,  7.5088516e-03, -4.5362808e-02,
          1.9269254e-02, -1.1452138e-02],
        [-4.3687463e-02, -3.5354652e-02,  4.2295184e-02,  4.0213589e-02,
          4.0062655e-02, -3.5295881e-02,  7.5088516e-03, -4.5362808e-02,
          1.9269254e-02, -1.1452138e-02],
        [-4.3687463e-02, -3.5354652e-02,  4.2295184e-02,  4.0213589e-02,
          4.0062655e-02, -3.5295881e-02,  7.5088516e-03, -4.5362808e-02,
          1.9269254e-02, -1.1452138e-02],
        [-4.3687463e-02, -3.5354652e-02,  4.2295184e-02,  4.0213589e-02,
          4.0062655e-02, -3.5295881e-02,  7.5088516e-03, -4.5362808e-02,
          1.9269254e-02, -1.1452138e-02],
        [ 4.5262575e-03,  1.7906535e-02,  5.2919015e-03,  6.7681558e-03,
         -2.4494044e-03,  3.6764745e-02, -4.5403149e-02,  2.9748883e-02,
          3.8932752e-02, -2.0737760e-03],
        [ 3.2885108e-02,  2.1046031e-02, -2.7203381e-02,  1.

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 7147, 9303, 4510, 7604], dtype=int32)

In [18]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>