<a href="https://colab.research.google.com/github/jothi08/Deeplearning_Feb21_2026/blob/main/Simple_RNN_IMDB/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#implementing word embedding with Keras Tensorflow

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
for words in sent:
  print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am a good developer
understand the meaning of words
your videos are good


In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[7198, 3946, 1068, 2580],
 [7198, 3946, 1068, 4477],
 [7198, 1933, 1068, 6018],
 [433, 894, 5978, 7153, 6490],
 [433, 894, 5978, 7153, 2914],
 [1974, 7198, 9593, 1068, 7631],
 [7275, 3918, 9788, 7153]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
#seq_len    = 100        # fixed padded/truncated sequence length
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7198 3946 1068 2580]
 [   0    0    0    0 7198 3946 1068 4477]
 [   0    0    0    0 7198 1933 1068 6018]
 [   0    0    0  433  894 5978 7153 6490]
 [   0    0    0  433  894 5978 7153 2914]
 [   0    0    0 1974 7198 9593 1068 7631]
 [   0    0    0    0 7275 3918 9788 7153]]


In [15]:
## feature representation
embed_dim=10 # embedding vector size

In [18]:


from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Input, Embedding

model = Sequential([
    keras.Input(shape=(sent_length,), dtype="int32"),          # explicit Input first
    Embedding(input_dim=voc_size, output_dim=embed_dim, mask_zero=True)  # no input_length here
])

model.compile(optimizer="adam", loss="mse")   # but consider adding a pooling/dense head


In [19]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step


array([[[-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [ 0.02153844, -0.00017027, -0.01205043, -0.00829945,
         -0.00955515,  0.03368864, -0.03431378, -0.02881943,
          0.01107868, -0.04519904],
        [-0.01824684, -0.03448318, -0.01104478, -0.01440362,
         -0.00407225, -0.00085859,  0.03606616, -0.00079081,
         -0.02431779, -0.02151382],
        [ 0.04414347, -0.03464342, -0.0074669 , -0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 7198, 3946, 1068, 2580], dtype=int32)

In [23]:
#If embedded_docs is already a NumPy array with shape (num_examples, sent_length), you can also select a batched slice:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[[-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [-0.00852411, -0.03608886,  0.04339329,  0.04423464,
         -0.02238514, -0.03816979,  0.03376993, -0.00259971,
          0.01177344,  0.04059348],
        [ 0.02153844, -0.00017027, -0.01205043, -0.00829945,
         -0.00955515,  0.03368864, -0.03431378, -0.02881943,
          0.01107868, -0.04519904],
        [-0.01824684, -0.03448318, -0.01104478, -0.01440362,
         -0.00407225, -0.00085859,  0.03606616, -0.00079081,
         -0.02431779, -0.02151382],
        [ 0.04414347, -0.03464342, -0.0074669 , -0.0